In [ ]:
1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
2.呈上題，將以上數列取出偶數。
3.呈1題，將數列取出3的倍數。

In [31]:
import numpy as np
n = input("請輸入陣列的最大值:")
print()

na = np.linspace(0, int(n) , int(n)+1) 
print("請列出從0到 %d 的公差為1的數列 " % (int(n)))
print(na)
print()

print("請列出從0到 %d 的公差為2的數列 " % (int(n)))
nb = np.arange(0, int(n) , 2) 
print(nb)
print()

print("請列出從0到 %d 的公差為3的數列 " % (int(n)))
nc = np.arange(0, int(n) , 3) 
print(nc)

請輸入陣列的最大值:20

請列出從0到 20 的公差為1的數列 
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20.]

請列出從0到 20 的公差為2的數列 
[ 0  2  4  6  8 10 12 14 16 18]

請列出從0到 20 的公差為3的數列 
[ 0  3  6  9 12 15 18]


In [ ]:
4.[簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

In [ ]:
#Answer：Array存放的資料類型都是同一類停，List可以存放不同類型的資料。

In [ ]:
5.請試著在程式中印出以下三個 NdArray 的屬性？
（屬性：ndim、shape、size、dtype、itemsize、length、type）

In [14]:
import numpy as np
list1 = [[1, 2, 3, 4, 5],[6, 7 ,8 ,9 ,10]]
my_array = np.array(list1)
x = len(my_array)
y = type(my_array)
print("my_array:", my_array,"\n")
print("my_array.ndim :",my_array.ndim, "\n")
print("my_array.shape:",my_array.shape, "\n")
print("my_array.size:", my_array.size, "\n")
print("my_array.dtype:", my_array.dtype, "\n")
print("my_array.itemsize:", my_array.itemsize, "\n")
print("my_array.length:", x, "\n")
print("my_array.type:",y, "\n")


my_array: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

my_array.ndim : 2 

my_array.shape: (2, 5) 

my_array.size: 10 

my_array.dtype: int32 

my_array.itemsize: 4 

my_array.length: 2 

my_array.type: <class 'numpy.ndarray'> 



In [ ]:
6.如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。

In [17]:
data = np.random.randint(10, size=(3,2,3))

print(data.tolist())
print(list(data))

[[[8, 0, 2], [1, 8, 3]], [[5, 9, 7], [7, 4, 3]], [[6, 1, 3], [8, 9, 1]]]
[array([[8, 0, 2],
       [1, 8, 3]]), array([[5, 9, 7],
       [7, 4, 3]]), array([[6, 1, 3],
       [8, 9, 1]])]


In [18]:
data1 = np.random.randint(10, size=(2,2))

print(data1.tolist())
print(list(data1))

[[7, 2], [9, 5]]
[array([7, 2]), array([9, 5])]


In [22]:
data2 = np.random.randint(10, size=3)

print(data2.tolist())
print(list(data2))

[0, 1, 9]
[0, 1, 9]
