# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [5]:
import numpy as np

a = np.arange(15).reshape(3, 5)
print('陣列a的內容如下：', '\n', a, '\n')

print('第一種將Array a 轉成List的方式: list(a) ')
print('list(a): ', list(a))
print()
print('第二種將Array a 轉成List的方式: a.tolist()')
print('tolist(): ', a.tolist())

陣列a的內容如下： 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

第一種將Array a 轉成List的方式: list(a) 
list(a):  [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]

第二種將Array a 轉成List的方式: a.tolist()
tolist():  [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [18]:
import numpy as np

a = np.random.randint(10, size=6) 
print('陣列a的內容如下：', '\n', a ,'\n')

print('a.ndim:', a.ndim)
print('a.shape:', a.shape)
print('a.size:', a.size)
print('a.dtype:', a.dtype)
print('a.itemsize:', a.itemsize)
print("len(a):", len(a))
print('type(a):', type(a))

陣列a的內容如下： 
 [8 1 5 4 6 9] 

a.ndim: 1
a.shape: (6,)
a.size: 6
a.dtype: int32
a.itemsize: 4
len(a): 6
type(a): <class 'numpy.ndarray'>


In [22]:
import numpy as np

b = np.random.randint(10, size=(3,4)) 

print('陣列b的內容如下：', '\n', b ,'\n')

print('b.ndim:', b.ndim)
print('b.shape:', b.shape)
print('b.size:', b.size)
print('b.dtype:', b.dtype)
print('b.itemsize:', b.itemsize)
print("len(b):", len(b))
print('type(b):', type(b))

陣列b的內容如下： 
 [[7 0 5 7]
 [2 7 9 4]
 [7 9 3 4]] 

b.ndim: 2
b.shape: (3, 4)
b.size: 12
b.dtype: int32
b.itemsize: 4
len(b): 3
type(b): <class 'numpy.ndarray'>


In [23]:
import numpy as np

c = np.random.randint(10, size=(2,3,2))  
print('陣列c的內容如下：', '\n', c ,'\n')

print('c.ndim:', c.ndim)
print('c.shape:', c.shape)
print('c.size:', c.size)
print('c.dtype:', c.dtype)
print('c.itemsize:', c.itemsize)
print("len(c):", len(c))
print('type(c):', type(c))

陣列c的內容如下： 
 [[[9 6]
  [6 3]
  [6 2]]

 [[1 4]
  [2 4]
  [0 9]]] 

c.ndim: 3
c.shape: (2, 3, 2)
c.size: 12
c.dtype: int32
c.itemsize: 4
len(c): 2
type(c): <class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [33]:
a = np.random.randint(10, size=6) 

print('陣列 a 的內容如下：', '\n', a, '\n')
print('陣列 a 轉成 a.tolist() :','\n', a.tolist(), '\n')
print('陣列 a 轉成 list(a)：','\n',list(a), '\n')


陣列 a 的內容如下： 
 [3 4 0 4 6 0] 

陣列 a 轉成 a.tolist() : 
 [3, 4, 0, 4, 6, 0] 

陣列 a 轉成 list(a)： 
 [3, 4, 0, 4, 6, 0] 



In [32]:
b = np.random.randint(10, size=(3,4)) 

print('陣列 b 的內容如下：', '\n', b, '\n')
print('陣列 b 轉成 b.tolist() :','\n', b.tolist(), '\n')
print('陣列 b 轉成 list(b)：','\n',list(b), '\n')


陣列 b 的內容如下： 
 [[2 9 1 2]
 [3 7 0 7]
 [9 0 2 1]] 

陣列 b 轉成 b.tolist() : 
 [[2, 9, 1, 2], [3, 7, 0, 7], [9, 0, 2, 1]] 

陣列 b 轉成 list(b)： 
 [array([2, 9, 1, 2]), array([3, 7, 0, 7]), array([9, 0, 2, 1])] 



In [31]:
c = np.random.randint(10, size=(2,3,2)) 

print('陣列 c 的內容如下：', '\n', c, '\n')
print('陣列 c 轉成 c.tolist() :','\n', c.tolist(), '\n')
print('陣列 c 轉成list(c)：','\n',list(c), '\n')

陣列 c 的內容如下： 
 [[[8 8]
  [1 0]
  [9 9]]

 [[2 1]
  [2 7]
  [0 0]]] 

陣列 c 轉成 c.tolist() : 
 [[[8, 8], [1, 0], [9, 9]], [[2, 1], [2, 7], [0, 0]]] 

陣列 c 轉成list(c)： 
 [array([[8, 8],
       [1, 0],
       [9, 9]]), array([[2, 1],
       [2, 7],
       [0, 0]])] 



In [34]:
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    else:
        return [tolist(obj) for obj in iterable]
    
print(tolist(a))
print(tolist(b))
print(tolist(c))

[3, 4, 0, 4, 6, 0]
[[2, 9, 1, 2], [3, 7, 0, 7], [9, 0, 2, 1]]
[[[8, 8], [1, 0], [9, 9]], [[2, 1], [2, 7], [0, 0]]]


In [39]:
def list(index):
    return index.tolist()


print(list(a))
print(list(b))
print(list(c))

[3, 4, 0, 4, 6, 0]
[[2, 9, 1, 2], [3, 7, 0, 7], [9, 0, 2, 1]]
[[[8, 8], [1, 0], [9, 9]], [[2, 1], [2, 7], [0, 0]]]


In [ ]:

作業-延伸題:

在array中，可以靈活應用索引幫助資料擷取 作業重點: 陣列的索引、切片、以及屬性，皆需要注意使用方式 陣列之中索引式由0開始請同學注意

1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。


In [40]:
import numpy as np
n = input("請輸入陣列的最大值:")
print()

na = np.linspace(0, int(n) , int(n)+1) 
print("請列出從0到 %d 的公差為1的數列 " % (int(n)))
print(na)
print()

print("請列出從0到 %d 的公差為2的數列 " % (int(n)))
nb = np.arange(0, int(n) , 2) 
print(nb)
print()

print("請列出從0到 %d 的公差為3的數列 " % (int(n)))
nc = np.arange(0, int(n) , 3) 
print(nc)

請輸入陣列的最大值:20

請列出從0到 20 的公差為1的數列 
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20.]

請列出從0到 20 的公差為2的數列 
[ 0  2  4  6  8 10 12 14 16 18]

請列出從0到 20 的公差為3的數列 
[ 0  3  6  9 12 15 18]
