In [18]:
import numpy as np
print("列出從1-30組合的5*6距陣:")
na = np.arange(1, 31).reshape(5,6)
print(na)
print()
print("列出所有被6除，餘數為1的索引")
print(na[1:5,0])

列出從1-30組合的5*6距陣:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]

列出所有被6除，餘數為1的索引
[ 7 13 19 25]
