# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [2]:
import numpy as np
import pandas as pd

print('np.zeros(2,3)')
print(np.zeros((2, 3)))
print()
print('np.empty(2.3)')
print(np.empty((2, 3)))

np.zeros(2,3)
[[0. 0. 0.]
 [0. 0. 0.]]

np.empty(2.3)
[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
Answer ： np.zeros的內容是全部為0的陣列。 np.empty的內容是全部都初始化的陣列。

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [11]:
# 記得先 Import 正確的套件
import numpy as np
from numpy.random import default_rng

a = default_rng()

A = a.standard_normal((2,3))
R = a.random((2,3))
I = a.integers(0, 10, size=(2,3))

print('a.standard_normal((2,3))')
print(A)
print()
print('a.random((2,3))')
print(R)
print()
print('a.integers(0, 10, size=(2,3))')
print(I)

a.standard_normal((2,3))
[[-0.31000219 -0.42780152  0.24677031]
 [ 0.17821005 -1.00215842  0.02615545]]

a.random((2,3))
[[0.26757538 0.53915712 0.12704488]
 [0.9762342  0.8878732  0.1410333 ]]

a.integers(0, 10, size=(2,3))
[[7 9 2]
 [4 3 8]]


In [4]:
# 參考解答

a = np.random.rand(2, 3)

'''
Your Code
'''

[[26.59948885 47.53904807 54.11469174]
 [70.68669942  6.86886691  4.57672874]]
[[27. 48. 54.]
 [71.  7.  5.]]
[[27. 48. 54.]
 [71.  7.  5.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [15]:
import numpy as np

m = 2
n = 8
a = np.random.rand(3, 3)
c = np.clip(a, m, n)
print(c)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [ ]:
作業目標
在一個陣列中放入多屬性陣列，進一步對陣列做運算
作業重點
在建立結構化陣列前需要先設定屬性，在做運算時須注意資料屬性

題目:
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]
rank_list = [8,1,5,4,7,6,2,3]
myopia_list = [True,True,False,False,True,True,False,False]

    將上列list依照['name', 'sex', 'weight', 'rank', 'myopia']順序擺入array，並且資料型態順序擺入[Unicode,Unicode,float,int,boolean]
    呈上題，將array中體重(weight)數據集取出算出全部平均體重
    呈上題，進一步算出男生(sex欄位是boy)平均體重、女生(sex欄位是girl)平均體重



In [17]:
import numpy as np

name = ['小明','小華','小菁','小美','小張','John','Mark','Tom']
sex = ['boy','boy','girl','girl','boy','boy','boy','boy']
weight = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]
rank = [8,1,5,4,7,6,2,3]
myopia = [True,True,False,False,True,True,False,False]

In [33]:
#將list中的資訊整理成陣列
dt = np.dtype({'names':('name', 'sex', 'weight', 'rank', 'myopia'),
               'formats':('U8', 'U8', float, int, bool)})
data = np.zeros(8, dtype = dt)
data['name'] = name
data['sex'] = sex
data['weight'] = weight
data['rank'] = rank
data['myopia'] = myopia

print(data)
print()
print('平均體重為：',data['weight'].mean())

[('小明', 'boy', 67.5, 8,  True) ('小華', 'boy', 75.3, 1,  True)
 ('小菁', 'girl', 50.1, 5, False) ('小美', 'girl', 45.5, 4, False)
 ('小張', 'boy', 80.8, 7,  True) ('John', 'boy', 90.4, 6,  True)
 ('Mark', 'boy', 78.4, 2, False) ('Tom', 'boy', 70.7, 3, False)]

平均體重為： 69.8375


In [46]:
boy_w = data[ data['sex'] == 'boy' ]['weight'] #取陣列data[weight]內容為boy
print('All boys weight :', boy_w)
print()
girl_w = data[ data['sex'] == 'girl' ]['weight']  #取陣列data[weight]內容為girl
print('All girls weight:',girl_w)
print()
boy_mean_weight = np.mean (boy_w, dtype=np.float64)
print('boys_mean_weight = ', boy_mean_weight)
print()
girl_mean_weight = np.mean (girl_w, dtype=np.float64)
print('girls_mean_weight = ', girl_mean_weight)
print()

All boys weight : [67.5 75.3 80.8 90.4 78.4 70.7]

All girls weight: [50.1 45.5]

boys_mean_weight =  77.18333333333332

girls_mean_weight =  47.8

