# [作業目標]

1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```

2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？

3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？

# 作業 

### 1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```


In [9]:
import numpy as np

a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] )

a1=np.reshape(a,(2, 2))

print(a + a)
print(a + b)
print(a + c)
print(a + d)
print(a1+ e)

[ 40  60  80 100]
[21 32 43 54]
[21 31 41 51]
[21 31 41 51]
[[21 32]
 [41 52]]


### 2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？


In [36]:
# 不用迴圈的情況下計算 (A+B)*(-A/2)
import numpy as np

A = np.ones(3)*1
B = np.ones(3)*2
C = np.array(A+B)
D = np.array(-A)/2
E = np.array(C)*D
print('array A+B=', '\n',C , '\n')
print('array -A/2=', '\n', D, '\n')
print('array  (A+B)*(-A/2) =', '\n', E, '\n')

array A+B= 
 [3. 3. 3.] 

array -A/2= 
 [-0.5 -0.5 -0.5] 

array  (A+B)*(-A/2) = 
 [-1.5 -1.5 -1.5] 



In [37]:
# 用迴圈的情況下計算 (A+B)*(-A/2)
import numpy as np

A = np.ones(3)*1
B = np.ones(3)*2

C = np.array(A+B)
D = np.array(-A)/2
C1 =  len(C)

for i in range(C1):
    E[i] = np.array(C[i]*D[i]) 
print('array (A+B)*(-A/2)=','\n')
print(E)

array (A+B)*(-A/2)= 

[-1.5 -1.5 -1.5]


### 3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？


In [39]:
A = np.ones((1,6))
B = np.ones((6,1))

print('array A is:', '\n', A, '\n')
print('array B is:', '\n', B, '\n')
print('array A*B is:', '\n', A*B, '\n' )




array A is: 
 [[1. 1. 1. 1. 1. 1.]] 

array B is: 
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]] 

array A*B is: 
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]] 

