# [作業目標]

1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```

2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？

3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？

# 作業 

### 1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```


In [6]:
import numpy as np

a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 

print('array a=',a,'\n')
print('array b=',b,'\n')
print('array c=',c,'\n')
print('array d=',d,'\n')

f= np.reshape(a,(2,2))

print('a+a=','\n',a + a,'\n')
print('a+b=','\n',a + b,'\n')
print('a+c=','\n',a + c,'\n')
print('a+d=','\n',a + d,'\n')
print('a+e=','\n',f + e,'\n')

array a= [20 30 40 50] 

array b= [1 2 3 4] 

array c= 1 

array d= [1] 

a+a= 
 [ 40  60  80 100] 

a+b= 
 [21 32 43 54] 

a+c= 
 [21 31 41 51] 

a+d= 
 [21 31 41 51] 

a+e= 
 [[21 32]
 [41 52]] 



### 2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？


In [8]:
A = np.ones(3)*1
B = np.ones(3)*2

print('Array A=','\n',A,'\n')
print('Array B=','\n',B,'\n')
print('Array (A + B) * (-A / 2)=')
print((A + B) * (-A / 2))

Array A= 
 [1. 1. 1.] 

Array B= 
 [2. 2. 2.] 

Array (A + B) * (-A / 2)=
[-1.5 -1.5 -1.5]


### 3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？


In [2]:
# 記得先 Import 正確的套件

import numpy as np


In [9]:
# 參考解答

A = np.ones((1,6))
B = np.ones((6,1))

print('Array A=','\n',A,'\n')
print('Array B=','\n',B,'\n')

print('Array A*B=','\n',A * B,'\n')
print('Array A@B=','\n',A @ B,'\n')

Array A= 
 [[1. 1. 1. 1. 1. 1.]] 

Array B= 
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]] 

Array A*B= 
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]] 

Array A@B= 
 [[6.]] 



In [ ]:
作業

題目:
運用投影片中的分貝公式回答下列問題。
1.正常的談話的聲壓為20000微巴斯卡，請問多少分貝?
2.30分貝的聲壓會是50分貝的幾倍?


In [1]:
import numpy as np 
#1.正常的談話的聲壓為20000微巴斯卡，請問多少分貝?
#60
V1 = 20000
V0 = 20
20*np.log10(V1/V0)

60.0

In [3]:
import numpy as np 
#2.30分貝的聲壓會是50分貝的幾倍?
#公式移項過後可以得到 V1 = 10^(GdB/20)*V0
#10倍
V1_30 = 10**(30/20)*V0
V1_50 = 10**(50/20)*V0
V1_30/V1_50

0.09999999999999999