# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [29]:
# 記得先 Import 正確的套件

import numpy as np

data = np.arange(12)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [59]:
for i in a-1:
    if (a[i] > 2) & (a[i] < 7):
        a[i] = -a[i]
        
print(a)

[ 1  2 -3 -4 -5 -6  7  8  9 10 11]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [35]:
A = np.random.rand(3, 6)
A

array([[0.21593469, 0.69780009, 0.40266551, 0.81620775, 0.47056591,
        0.78680711],
       [0.38820176, 0.64195817, 0.54020725, 0.79543075, 0.26136648,
        0.09285435],
       [0.49265438, 0.27780805, 0.30403838, 0.7450431 , 0.77072972,
        0.40880788]])

In [57]:
print('列出大於0.5的數值','\n',A[A>0.5],'\n')
len(A[A>0.5])
print('大於0.5的數值共有',len(A[A>0.5]),'個','\n')


列出大於0.5的數值 
 [0.69780009 0.81620775 0.78680711 0.64195817 0.54020725 0.79543075
 0.7450431  0.77072972] 

大於0.5的數值共有 8 個 



In [ ]:
題目:
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])
上3列共六位同學的英文、數學、國文成績，第一個元素代表第一位同學，舉例第一位同學英文55分、數學60分、國文65分，今天第五位同學因某原因沒來考試，
導致數學成績缺值，運用上列數據回答下列問題。

    請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?
    第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?
    用補考後資料找出與國文成績相關係數最高的學科?



In [58]:
import numpy as np
import pandas as pd

english_score =[55,89,76,65,48,70]
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = [65, 90, 82, 72, 66, 77]

print('英文科的最高分數是:',max(english_score) , '\n')
print('英文科的最低分數是:',min(english_score) , '\n')
print('英文科的標準差是:',np.std(english_score, ddof = 1) , '\n')

print('數學科的最高分數是:',max(math_score) , '\n')
print('數學科的最低分數是:',min(math_score) , '\n')
print('數學科的標準差是:',np.std(math_score, ddof = 1) , '\n')

print('國文科的最高分數是:',max(chinese_score) , '\n')
print('國文科的最低分數是:',min(chinese_score) , '\n')
print('國文科的標準差是:',np.std(chinese_score, ddof = 1) , '\n')

#第五位同學數學補考成績是55，請計算數學科的最高分、最低分，標準差

print('數學科第五位同學補考成績是55，重新計算最高分、最低分和標準差如下:\n')
math_score[4] = 55
print('數學科的最高分數是:',max(math_score) , '\n')
print('數學科的最低分數是:',min(math_score) , '\n')
print('數學科的標準差是:',np.std(math_score, ddof = 1) , '\n')

#用補考後成績找出與國文科相關係數最高學科

print('數學補考後的成績與國文科相關最高係數的學科是:\n')

A = np.vstack((chinese_score, english_score))
B = np.vstack((chinese_score, math_score))

print('國文與英文科的相關係數是:\n', np.corrcoef(A))
print()
print('國文與數學科的相關係數是:\n',np.corrcoef(B))
print()

英文科的最高分數是: 89 

英文科的最低分數是: 48 

英文科的標準差是: 14.716204220744787 

數學科的最高分數是: 85.0 

數學科的最低分數是: 60.0 

數學科的標準差是: nan 

國文科的最高分數是: 90 

國文科的最低分數是: 65 

國文科的標準差是: 9.66781602362533 

數學科第五位同學補考成績是55，重新計算最高分、最低分和標準差如下:

數學科的最高分數是: 85.0 

數學科的最低分數是: 55.0 

數學科的標準差是: 10.801234497346433 

數學補考後的成績與國文科相關最高係數的學科是:

國文與英文科的相關係數是:
 [[1.         0.97792828]
 [0.97792828 1.        ]]

國文與數學科的相關係數是:
 [[1.         0.74056803]
 [0.74056803 1.        ]]

