# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [2]:
import numpy as np
a = np.arange(1,12)
print(a)



[ 1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
for i in a-1:
    if (a[i] > 2) & (a[i] < 7):
        a[i] = -a[i]
        
print(a)

### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [17]:
import numpy as np

A = np.random.rand(3, 6)

print(A)
print(A[A>0.5].size)

[[0.53454009 0.16918675 0.065203   0.14002532 0.456514   0.29743905]
 [0.66611619 0.60577602 0.91135781 0.45490331 0.20206647 0.01384813]
 [0.78582621 0.12978975 0.0309115  0.57971065 0.58735924 0.35697334]]
7
