# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [1]:
import numpy as np
a=np.array([1,2,5,3,8])
print('a.sum() :',a.sum(),'\n') 
print('np.sum(a) : ',np.sum(a), '\n')
print('sum(a) :',sum(a),'\n') 


a.sum() : 19 

np.sum(a) :  19 

sum(a) : 19 



In [ ]:
Answer: sum() 是 python 內建的函式，所有型態皆可以用。np.sum(a) 跟 a.sum() 是陣列專有的函式，差別在於定義在 np 或是 array 底下。

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [4]:
import numpy as np

A = np.random.random((5,5))
A = (A - A.min()) / (A.max() - A.min())
print(A)

[[0.22858706 0.54198252 0.80626453 0.82339249 0.03838028]
 [0.4838909  0.51347229 0.23881846 0.30092776 1.        ]
 [0.72773031 0.96587491 0.48567476 0.57244459 0.65430548]
 [0.77176821 0.68442238 0.35061677 0.31144973 0.09728524]
 [0.32806011 0.77825039 0.3686094  0.21163824 0.        ]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [6]:
import numpy as np
import pandas as pd

B = np.random.random(10)
B[B.argmax()] = -1
print (B)

[-1.          0.8718249   0.44579336  0.76992066  0.58665414  0.76806139
  0.88194555  0.82781983  0.22093977  0.61146265]


In [ ]:
作業

題目:
1.將下列陣列(array1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
2.呈上題的array，找出被6除餘1的數的索引

In [7]:
import numpy as np

array1 = np.array(range(30))
reshape_array = array1.reshape(5,6,order="F")
reshape_array

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

In [8]:
np.where(reshape_array%6==1)

(array([0, 1, 2, 3, 4], dtype=int64), array([5, 0, 1, 2, 3], dtype=int64))