# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [4]:
import numpy as np 

a = np.arange(6)

print(a.sum()) # 15
print(np.sum(a)) # 15
print(sum(a)) # 15

15
15
15


In [ ]:
回答:
print(a.sum()) ；將array a的內容值加總，是python內建的函式
print(np.sum(a)) : 是python針對array設定的函式
print(sum(a)) ： 同樣是python針對array或是np所設定的函數

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [6]:
import numpy as np

A = np.random.random((5,5))
print(A)



[[0.06678214 0.6992381  0.23233691 0.15980271 0.38471147]
 [0.48412479 0.06392564 0.11691578 0.49551006 0.1385766 ]
 [0.34583019 0.44242583 0.55627673 0.52540505 0.30823748]
 [0.62678262 0.78916371 0.75930116 0.5477645  0.80342123]
 [0.80871244 0.78371435 0.49821459 0.40645914 0.36503384]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [21]:
import numpy as np

A = np.random.randint(1,10,10)
A_max = A.max()

print('陣列A的原始內容：', A)
print()
print('原始陣列中的最大值為:', A_max)
print()

for i in np.arange(np.size(A)):
    if A[i] >= A_max:
        A[i] = -1
        
print('將最大值更換為-1之後的陣列值為:', A)



陣列A的原始內容： [7 6 9 8 4 2 3 3 5 2]

原始陣列中的最大值為: 9

將最大值更換為-1之後的陣列值為: [ 7  6 -1  8  4  2  3  3  5  2]
