In [3]:
import numpy as np
import io as f
import pandas as pd

array1 = np.array(range(30))
array2 = np.array([2,3,5])
print('array1的元素如下:\n')
print(array1)
print()
print('array2的元素如下:\n')
print(array2)
print()
file = 'my_file.npz'
np.savez(file, a = array1 , b = array2, delimiter = '\n')
print('將兩個array存成檔案 %s \n' % (f))
f1 = np.load(file)
print('讀取出含有array1、array2的陣列檔案 %s 的元素如下:\n' % (f))
print(f1['a'])
print(f1['b'])
print()
print('*******************************************************')

name = np.loadtxt('names.txt', dtype='str', encoding='bytes')
one_array = np.load('one_array.npy')
data = np.genfromtxt('test.csv', delimiter=',')
test_pny = np.load('test.npy',)
np.savez(file, a = array1 , b = array2, c = name, d = one_array, e = data, f = test_pny, delimiter = '\n') 

all = np.load(file)
print('讀取出包含所有檔案的pnz檔案的的元素如下:\n')
print(all['a'])
print()
print(all['b'])
print()
print(all['c'])
print()
print(all['d'])
print()
print(all['e'])
print()
print(all['f'])

# e = np.open('one_array.npy')
# print(e)


array1的元素如下:

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

array2的元素如下:

[2 3 5]

將兩個array存成檔案 <module 'io' from 'C:\\ProgramData\\Anaconda3\\lib\\io.py'> 

讀取出含有array1、array2的陣列檔案 <module 'io' from 'C:\\ProgramData\\Anaconda3\\lib\\io.py'> 的元素如下:

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]

*******************************************************
讀取出包含所有檔案的pnz檔案的的元素如下:

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[2 3 5]

['a,b,c' '1,2,3' '4,5,6' '7,8,9']

[1 2]

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]

[1 2]
