# [作業目標]

1. 請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。

2. 如何從一個陣列中，找出出現頻率最高的數值與位置？

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. 請比較對一個 1000 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。




In [1]:
import numpy as np

Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)

In [2]:
%timeit -n 10 a = 2
for a in Z:
    for row in a:
        for b in row:
            b=b+1

34.3 ns ± 10.5 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [3]:
%timeit -n 10 a = 2
for c in Z.flat:   # 默認参数為"C"，即按照行進行重组。返回一个迭代器，可以遍歷数组中的每一个元素
    c=c+1

34.3 ns ± 10.5 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [4]:
%timeit -n 10 a = 2
for d in np.nditer(Z):   #按照行進行重组
    d=d+1

44.3 ns ± 15 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


### 2. 如何從一個陣列中，找出出現頻率最高的數值與位置？


In [5]:
Z=np.random.randint(0,10,50)
print('Array Z =')
print(Z)


Array Z =
[8 5 3 3 6 1 3 0 1 2 8 4 7 6 4 5 7 5 7 6 3 1 8 2 5 9 5 0 4 4 7 6 5 1 1 4 9
 0 6 4 4 1 5 0 4 9 6 3 1 7]


In [11]:
loc = np.bincount(Z.ravel()).argmax()
ans = np.array(np.where(Z == loc))
print("The most frequent value: ", loc)
print("location: ", ans)

The most frequent value:  4
location:  [[11 14 28 29 35 39 40 44]]


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [24]:
a = np.random.randint(10, size=6) 
print('array a= ')
print(a)
print()

print('a.tolist()=',a.tolist(), '\n')
print('list(a)=',list(a), '\n')


b = np.random.randint(10, size=(3,4)) 
print('b array = ')
print(b)
print()

print('b.tolist()=', b.tolist())
print()
print('list(b)=',list(b))
print()



c = np.random.randint(10, size=(2,3,2)) 
print('c array = ')
print(c)
print()

print('c.tolist()=',c.tolist())
print()
print('list(c)=',list(c))
print()


array a= 
[9 7 9 6 9 0]

a.tolist()= [9, 7, 9, 6, 9, 0] 

list(a)= [9, 7, 9, 6, 9, 0] 

b array = 
[[2 8 7 9]
 [6 1 0 7]
 [2 4 5 7]]

b.tolist()= [[2, 8, 7, 9], [6, 1, 0, 7], [2, 4, 5, 7]]

list(b)= [array([2, 8, 7, 9]), array([6, 1, 0, 7]), array([2, 4, 5, 7])]

c array = 
[[[2 0]
  [5 3]
  [8 4]]

 [[0 4]
  [6 1]
  [2 1]]]

c.tolist()= [[[2, 0], [5, 3], [8, 4]], [[0, 4], [6, 1], [2, 1]]]

list(c)= [array([[2, 0],
       [5, 3],
       [8, 4]]), array([[0, 4],
       [6, 1],
       [2, 1]])]



In [26]:
#利用 list(...) 實現 a.tolist() 的效果
print(list(b.flat))
print(list(c.flat))

[2, 8, 7, 9, 6, 1, 0, 7, 2, 4, 5, 7]
[2, 0, 5, 3, 8, 4, 0, 4, 6, 1, 2, 1]


In [ ]:
array1 = np.array([[10, 8], [3, 5]])


    運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
    運用上列array計算特徵值、特徵向量?
    運用上列array計算SVD?


In [32]:
import numpy as np

# 運用上列array計算反矩陣，乘上反矩陣，並觀察矩陣是否為單位矩陣?
print('陣列A的元素如下:')
A = np.array([[10,8],[3,5]])
print(A,'\n')

print('陣列A的反矩陣的計算結果如下:')
B = np.linalg.inv(A)
print(B,'\n')

print('將兩個陣列相乘的結果如下:')
C = np.dot(A,B)
np.linalg.det(C)
print(C, '\n')

# 運用上列array計算特徵值、特徵向量?
print('計算出的特徵值如下:')
E = np.linalg.eig(A)
print(E, '\n')

print('特徵值為:')
print(E[0], '\n')

print('特徵向量為:')
print(E[1], '\n')

# 運用上列array計算SVD。
print('計算出來的SVD值如下:\n', '\n')
U,sigma,VT = np.linalg.svd(A)
print('U = ', U, '\n')

print('sigma = ', sigma, '\n')
print('VT = ', VT, '\n')

陣列A的元素如下:
[[10  8]
 [ 3  5]] 

陣列A的反矩陣的計算結果如下:
[[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]] 

將兩個陣列相乘的結果如下:
[[1. 0.]
 [0. 1.]] 

計算出的特徵值如下:
(array([13.,  2.]), array([[ 0.93632918, -0.70710678],
       [ 0.35112344,  0.70710678]])) 

特徵值為:
[13.  2.] 

特徵向量為:
[[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]] 

計算出來的SVD值如下:
 

U =  [[-0.91663818 -0.39971796]
 [-0.39971796  0.91663818]] 

sigma =  [13.94721714  1.86417116] 

VT =  [[-0.74319741 -0.6690722 ]
 [-0.6690722   0.74319741]] 

