In [38]:
import numpy as np

# 運用上列array計算反矩陣，乘上反矩陣，並觀察矩陣是否為單位矩陣?
print('陣列A的元素如下:\n')
A = np.array([[10,8],[3,5]])
print(A,'\n')

print('陣列A的反矩陣的計算結果如下:\n')
B = np.linalg.inv(A)
print(B,'\n')

print('將兩個陣列相乘的結果如下:')
C = np.dot(A,B)
np.linalg.det(C)
print(C, '\n')

# 運用上列array計算特徵值、特徵向量?
print('計算出的特徵值如下:')
E = np.linalg.eig(A)
print(E, '\n')

print('特徵值為:')
print(E[0], '\n')

print('特徵向量為:')
print(E[1], '\n')

# 運用上列array計算SVD。
print('計算出來的SVD值如下:\n', '\n')
U,sigma,VT = np.linalg.svd(A)
print('U = ', U, '\n')
print('sigma = ', sigma, '\n')
print('VT = ', VT, '\n')

陣列A的元素如下:

[[10  8]
 [ 3  5]] 

陣列A的反矩陣的計算結果如下:

[[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]] 

將兩個陣列相乘的結果如下:
[[1. 0.]
 [0. 1.]] 

計算出的特徵值如下:
(array([13.,  2.]), array([[ 0.93632918, -0.70710678],
       [ 0.35112344,  0.70710678]])) 

特徵值為:
[13.  2.] 

特徵向量為:
[[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]] 

計算出來的SVD值如下:
 

U =  [[-0.91663818 -0.39971796]
 [-0.39971796  0.91663818]] 

sigma =  [13.94721714  1.86417116] 

VT =  [[-0.74319741 -0.6690722 ]
 [-0.6690722   0.74319741]] 

